import Logo from '@/components/Logo';
import Navigation from '@/components/Navigation';

export const metadata = {
  title: 'Next.js project: The Wild Oasis',
  description: 'the-wild-oasis-website Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>Copyright by The Wild Oasis Team</footer>
      </body>
    </html>
  );
}
